package kr.or.connect.reservation.dao;

public class DisplayInfoSqls {
	public static final String GET_DISPLAY_INFO_ONE = 
			"SELECT DISPLAY_INFO.PRODUCT_ID AS PRODUCTID, " + 
			"	CATEGORY.ID AS CATEGORYID, " + 
			"	DISPLAY_INFO.ID AS DISPLAYINFOID, " + 
			"	CATEGORY.NAME AS CATEGORYNAME, " + 
			"	PRODUCT.DESCRIPTION AS PRODUCTDESCRIPTION, " + 
			"	PRODUCT.CONTENT AS PRODUCTCONTENT, " + 
			"	PRODUCT.EVENT AS PRODUCTEVENT, " + 
			"	DISPLAY_INFO.OPENING_HOURS AS OPENINGHOURS, " + 
			"	DISPLAY_INFO.PLACE_NAME AS PLACENAME, " + 
			"	DISPLAY_INFO.PLACE_LOT AS PLACELOT, " + 
			"	DISPLAY_INFO.PLACE_STREET AS PLACESTREET, " + 
			"	DISPLAY_INFO.TEL AS TELEPHONE, " + 
			"	DISPLAY_INFO.HOMEPAGE AS HOMEPAGE, " + 
			"	DISPLAY_INFO.EMAIL AS EMAIL, " + 
			"	DISPLAY_INFO.CREATE_DATE AS CREATEDATE, " + 
			"	DISPLAY_INFO.MODIFY_DATE AS MODIFYDATE " + 
			"FROM DISPLAY_INFO " + 
			"JOIN PRODUCT ON PRODUCT.ID = DISPLAY_INFO.PRODUCT_ID " + 
			"JOIN CATEGORY ON CATEGORY.ID = PRODUCT.CATEGORY_ID " + 
			"WHERE DISPLAY_INFO.ID = :displayInfoId"; 

	
	public static final String GET_DISPLAY_IMAGES_BY_DISPLAY_INFO_ID = 
			"SELECT DISPLAY_INFO_IMAGE.ID AS DISPLAYINFOIMAGEID, " + 
			"	DISPLAY_INFO_IMAGE.DISPLAY_INFO_ID AS DISPLAYINFOID, " + 
			"	DISPLAY_INFO_IMAGE.FILE_ID AS FILEID, " + 
			"	FILE_INFO.FILE_NAME AS FILENAME, " + 
			"	FILE_INFO.SAVE_FILE_NAME AS DISPLAYINFOSAVEFILENAME, " + 
			"	FILE_INFO.CONTENT_TYPE AS CONTENTTYPE, " + 
			"	FILE_INFO.DELETE_FLAG AS DELETEFLAG, " + 
			"	FILE_INFO.CREATE_DATE AS CREATEDATE, " + 
			"	FILE_INFO.MODIFY_DATE AS MODIFYDATE " + 
			"FROM DISPLAY_INFO_IMAGE " + 
			"JOIN FILE_INFO ON FILE_INFO.ID = DISPLAY_INFO_IMAGE.FILE_ID " + 
			"WHERE DISPLAY_INFO_IMAGE.DISPLAY_INFO_ID = :displayInfoId";
	
	public static final String  GET_PRODUCT_ID_BY_DISPLAY_INFO_ID = 
			"SELECT PRODUCT_ID " +
			"FROM DISPLAY_INFO " +
			"WHERE ID = :displayInfoId";
 
}
