package kr.or.connect.reservation.dao;

public class MyReservationDaoSqls {

	public static final String SELECT_TOTAL_RESERVATION_COUNT_BY_EMAIL = 
			"SELECT COUNT(*) FROM RESERVATION_INFO WHERE RESERVATION_EMAIL = :reservationEmail";
	
	public static final String SELECT_TOTAL_RESERVATION_BY_EMAIL = 
			"SELECT SUM(D.COUNT * E.PRICE) AS TICKETPRICE," + 
			"	SUM(D.COUNT) AS TICKETCOUNT, " + 
			"	C.PLACE_NAME AS PLACENAME, " + 
			"	C.PLACE_LOT AS PLACELOT, " + 
			"	C.PLACE_STREET AS PLACESTREET, " + 
			"	B.ID AS PRODUCTID, " + 
			"	B.DESCRIPTION AS DESCRIPTION, " + 
			"	A.ID AS RESERVATIONID, " + 
			"	A.CANCEL_FLAG AS CANCELFLAG, " + 
			"	A.RESERVATION_DATE AS RESERVATIONDATE " + 
			"FROM RESERVATION_INFO A JOIN PRODUCT B ON A.PRODUCT_ID = B.ID " + 
			"	JOIN DISPLAY_INFO C ON A.DISPLAY_INFO_ID = C.ID " + 
			"	JOIN RESERVATION_INFO_PRICE D ON A.ID = D.RESERVATION_INFO_ID " + 
			"	JOIN PRODUCT_PRICE E ON D.PRODUCT_PRICE_ID = E.ID " + 
			"WHERE A.RESERVATION_EMAIL = :reservationEmail " +
			"GROUP BY A.ID";
	
	public static final String SELECT_TICKET_INFO = 
			"SELECT B.PRICE_TYPE_NAME AS PRICETYPENAME, " + 
			"	B.PRICE AS PRICE, " + 
			"	A.COUNT AS COUNT " + 
			"FROM RESERVATION_INFO_PRICE A JOIN PRODUCT_PRICE B ON A.PRODUCT_PRICE_ID = B.ID " + 
			"WHERE A.RESERVATION_INFO_ID = :reservationId ";

	
	public static final String GET_TICKETINFO_BY_RESERVATION_ID = 
			"SELECT C.PRICE_TYPE_NAME AS PRICETYPENAME, " + 
			"	B.COUNT AS COUNT, " + 
			"	C.PRICE AS PRICE " + 
			"FROM RESERVATION_INFO A LEFT JOIN RESERVATION_INFO_PRICE B ON A.ID  = B.RESERVATION_INFO_ID " + 
			"	LEFT JOIN PRODUCT_PRICE C ON B.PRODUCT_PRICE_ID = C.ID " + 
			"WHERE A.ID = :reservationId";
	
	public static final String SELECT_MYLIST_BY_RESERVATIOM_ID = 
			"SELECT SUM(D.COUNT * E.PRICE) AS TICKETPRICE, " + 
			"	SUM(D.COUNT) AS TICKETCOUNT, " + 
			"	C.PLACE_NAME AS PLACENAME, " + 
			"	C.PLACE_LOT AS PLACELOT, " + 
			"	C.PLACE_STREET AS PLACESTREET, " + 
			"	B.ID AS PRODUCTID, " + 
			"	B.DESCRIPTION AS DESCRIPTION, " + 
			"	A.ID AS RESERVATIONID, " + 
			"	A.CANCEL_FLAG AS CANCELFLAG, " + 
			"	A.RESERVATION_DATE AS RESERVATIONDATE " + 
			"FROM RESERVATION_INFO A JOIN PRODUCT B ON A.PRODUCT_ID = B.ID " + 
			"	JOIN DISPLAY_INFO C ON A.DISPLAY_INFO_ID = C.ID " + 
			"	JOIN RESERVATION_INFO_PRICE D ON A.ID = D.RESERVATION_INFO_ID " + 
			"	JOIN PRODUCT_PRICE E ON D.PRODUCT_PRICE_ID = E.ID " + 
			"WHERE A.ID = :reservationId " + 
			"GROUP BY A.ID ";
	
	public static final String UPDATE_RESERVATION_CANCELFLAG = 
			"UPDATE RESERVATION_INFO SET CANCEL_FLAG = 1 WHERE ID = :reservationId ";
}
