package kr.or.connect.reservation.dao;

public class ProductDaoSqls {
	
	public static final String GET_COUNT_PRODUCT = 
			"SELECT COUNT(*) AS TOTALCOUNT FROM DISPLAY_INFO";
	
	public static final String GET_COUNT_PRODUCT_BY_CATEGORY = 
			"SELECT COUNT(*) AS TOTALCOUNT " + 
			"FROM DISPLAY_INFO JOIN PRODUCT " + 
			"ON DISPLAY_INFO.PRODUCT_ID = PRODUCT.ID " + 
			"WHERE PRODUCT.CATEGORY_ID = :categoryId";
	
	public static final String GET_PRODUCT_LIST = 
			"SELECT PRODUCT.ID AS PRODUCTID, " + 
			"	DISPLAY_INFO.ID AS DISPLAYINFOID, " + 
			"	DISPLAY_INFO.PLACE_NAME AS PLACENAME, " + 
			"	PRODUCT.DESCRIPTION AS PRODUCTDESCRIPTION, " + 
			"	PRODUCT.CONTENT AS PRODUCTCONTENT," +
			"	FILE_INFO.SAVE_FILE_NAME AS PRODUCTIMAGEURL " + 
			"FROM PRODUCT " + 
			"JOIN DISPLAY_INFO ON PRODUCT.ID = DISPLAY_INFO.PRODUCT_ID " + 
			"JOIN PRODUCT_IMAGE ON PRODUCT.ID = PRODUCT_IMAGE.PRODUCT_ID " + 
			"JOIN FILE_INFO ON PRODUCT_IMAGE.FILE_ID = FILE_INFO.ID " + 
			"WHERE PRODUCT_IMAGE.TYPE = 'TH' " + 
			"LIMIT :start, :limit";
	
	public static final String GET_PRODUCT_LIST_BY_CATEGORY = 
			"SELECT PRODUCT.ID AS PRODUCTID, " + 
			"	DISPLAY_INFO.ID AS DISPLAYINFOID, " + 
			"	DISPLAY_INFO.PLACE_NAME AS PLACENAME, " + 
			"	PRODUCT.DESCRIPTION AS PRODUCTDESCRIPTION, " + 
			"	PRODUCT.CONTENT AS PRODUCTCONTENT, " +
			"	FILE_INFO.SAVE_FILE_NAME AS PRODUCTIMAGEURL " + 
			"FROM PRODUCT " + 
			"JOIN DISPLAY_INFO ON PRODUCT.ID = DISPLAY_INFO.PRODUCT_ID " + 
			"JOIN PRODUCT_IMAGE ON PRODUCT.ID = PRODUCT_IMAGE.PRODUCT_ID " + 
			"JOIN FILE_INFO ON PRODUCT_IMAGE.FILE_ID = FILE_INFO.ID " + 
			"WHERE PRODUCT_IMAGE.TYPE = 'TH' AND PRODUCT.CATEGORY_ID = :categoryId " + 
			"LIMIT :start, :limit";			

	public static final String GET_PRODUCT_IMAGES_BY_PRODUCT_ID = 
		    "SELECT PRODUCT_IMAGE.PRODUCT_ID AS PRODUCTID, " + 
		    "	PRODUCT_IMAGE.ID AS PRODUCTIMAGEID, " + 
		    "	PRODUCT_IMAGE.TYPE AS TYPE, " + 
		    "	FILE_INFO.ID AS FILEID, " + 
		    "	FILE_INFO.FILE_NAME AS FILENAME, " + 
		    "	FILE_INFO.SAVE_FILE_NAME AS PRODUCTSAVEFILENAME, " + 
		    "	FILE_INFO.CONTENT_TYPE AS CONTENTTYPE, " + 
		    "	FILE_INFO.DELETE_FLAG AS DELETEFLAG, " + 
		    "	FILE_INFO.CREATE_DATE AS CREATEDATE, " + 
		    "	FILE_INFO.MODIFY_DATE AS MODIFYDATE " + 
		    "FROM PRODUCT_IMAGE " + 
		    "JOIN FILE_INFO ON PRODUCT_IMAGE.FILE_ID = FILE_INFO.ID " + 
		    "WHERE  PRODUCT_ID = :productId " + 
		    "AND (TYPE = 'MA' OR TYPE = 'ET' )";
	
	public static final String GET_PRODUCT_PRICE = 
		    "SELECT ID AS PRODUCTPRICEID, " + 
		    "	PRODUCT_ID AS PRODUCTID, " + 
		    "	PRICE_TYPE_NAME AS PRICETYPENAME, " + 
		    "	PRICE, " + 
		    "	DISCOUNT_RATE AS DISCOUNTRATE,  " + 
		    "	CREATE_DATE AS CREATEDATE, " + 
		    "	MODIFY_DATE AS MODIFYDATE " + 
		    "FROM   PRODUCT_PRICE " + 
		    "WHERE  PRODUCT_ID = :productId " + 
		    "ORDER BY ID DESC ";

}
